### ISSUE TITLE
[error] GenServer :importer terminating

### ISSUE THREAD

**Issue by theshock9** [iotaledger/chronicle#6]
Got this error when importing the DB Files

```
20:01:29.776 [info] Importer started
20:01:29.776 [info] Importing 6000 file
20:01:54.347 [info] Finished one dmp
20:01:54.500 [error] GenServer :importer terminating
** (UndefinedFunctionError) function File.close/0 is undefined or private
    (elixir) File.close()
    (core) lib/utils/importer/importer.ex:211: Core.Utils.Importer.process_dmp?/1
    (core) lib/utils/importer/importer.ex:25: Core.Utils.Importer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :finished_one
```

I try to skip this file and go to the next one (13157) and got the same result

Did i miss something?

Thx

**Comment by LouayKamel** [comment]
Thanks for reporting, looking into it.

**Comment by LouayKamel** [comment]
I'm closing this for now!

**Comment by theshock9** [comment]
Hi.

It Worked for the 6000.dmp
Next dmp... next error

```
00:29:06.567 [info] Starting the importing script
00:29:36.568 [info] Importer started
00:29:36.568 [info] Importing 13157 file
00:29:36.571 [error] GenServer :importer terminating
** (ArgumentError) argument error
    :erlang.binary_to_integer("")
    (core) lib/utils/converter/converter.ex:164: Core.Utils.Converter.line_81_to_tx_object/1
    (core) lib/utils/importer/importer.ex:169: Core.Utils.Importer.fetch_bundle_81/2
    (core) lib/utils/importer/importer.ex:59: Core.Utils.Importer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:fetch_bundle_81, false}
```

**Comment by LouayKamel** [comment]
@theshock9 pls check now

**Comment by theshock9** [comment]
K, now its loaded in the Exporter

But i got a lot this errors


```
 "INSERT INTO tangle.edge (v1,lb,ts,v2,ex,ix,el,lx) VALUES (?,30,?,?,?,?,?,?)"}
{"inserter",
 %OverDB.Protocol.V4.Frames.Responses.Error{
   message: "Operation timed out for system.batchlog - received only 0 responses from 1 CL=ONE.",
   reason: :write_timeout
 },
```
```
 "INSERT INTO tangle.edge (v1,lb,ts,v2,ex,ix) VALUES (?,60,0,varintAsBlob(0),varintAsBlob(0),0)"}
{"inserter",
 %OverDB.Protocol.V4.Frames.Responses.Error{
   message: "Operation timed out for system.batchlog - received only 0 responses from 1 CL=ONE.",
   reason: :write_timeout
 },
```

But anyway some TX are imported

**Comment by theshock9** [comment]
Thank you for your support

I have a SAS Raid 5 with 4 x 4 TB and got a Write Speed of 2000MB/s
The only Problem in my system now is the Memory. 12GB is not enough.
More is on the way.

But I made the changes you suggested. Test is runnung.

**Comment by theshock9** [comment]
Okay, something's weird.
Importing the dmp files is stuck on 13157. 
```
22:54:45.940 [info] Importer started
22:54:45.943 [info] Importing 6000 file
22:54:45.958 [info] Starting broker app
22:55:02.120 [info] Imported 6000
22:55:02.121 [info] Importing 13157 file
```
and thats it. Nothing change. No message about any error

Some hints?

THX

BTW, memory is upgraded and Scylla runs fine now ;)

**Comment by LouayKamel** [comment]
@theshock9 it shouldn't take more than a few seconds I'm investigating now.
would you please share with me the result of this command in elixir shell `:sys.get_state(Process.whereis(:importer))`

**Comment by theshock9** [comment]
Yeah, but the whole day?

Here is the result

```
iex(1)> :sys.get_state(Process.whereis(:importer)).pending
** (exit) exited in: :sys.get_state(nil)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) sys.erl:335: :sys.send_system_msg/2
    (stdlib) sys.erl:136: :sys.get_state/1
```

**Comment by LouayKamel** [comment]
@theshock9, I pushed a commit, please follow this now!
- use cqlsh in scylla node to drop the tangle keyspace, cqlsh command: `DROP KEYSPACE tangle;`
- clone chronicle and import everything again.

The first dmps are small should not take more than a few mins.
I added a monitor logic which will log into chronicle shell the recent amount of imported bundles,
this will be helpful for large dmp files, for instance:
```
...
[info] Importing 13157 file
[info] Imported 13157
[info] Importing 18675 file
[info] In progress: 18675.dmp; Loaded 159291 bundles
[info] Imported the last dmp file 18675
[info] Done: total 226646 bundles
```
Please report back if the importer stuck in the same dmp file and amount.
[info] In progress: **x**.dmp; Loaded **amount** bundles

**Comment by theshock9** [comment]
@LouayKamel, i get an error by "mix compile"

==> broker
Compiling 19 files (.ex)

22:42:22.210 [warn]  The on_load function for module Elixir.Nifs returned:
{{:badmatch, {:error, {:load_failed, 'Failed to load NIF library: \'/home/detshok/chronicle/_build/dev/lib/broker/priv/nifs.so: cannot open shared object file: No such file or directory\''}}}, [{Nifs, :init, 0, [file: 'lib/nifs.ex', line: 5]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', line: 1340]}]}

```

22:42:22.239 [error] Process #PID<0.993.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'/home/xxx/chronicle/_build/dev/lib/broker/priv/nifs.so: cannot open shared object file: No such file or directory\''}}
    lib/nifs.ex:5: Nifs.init/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
```
This Folder is empty "chronicle/_build/dev/lib/broker/priv/"

**Comment by theshock9** [comment]
***Edit. It´s not "mix compile"! It´s "mix deps.compile"... sorry

**Comment by theshock9** [comment]
I fix it by my self! Found the file in the Backup folder from Chronicle.

```
23:44:12.828 [info] Imported 13157
23:44:12.829 [info] Importing 18675 file
23:44:49.040 [info] Imported 18675
23:44:49.041 [info] Importing 61491 file
23:48:10.354 [info] In progress: 61491.dmp; Loaded 619941 bundles
```

Looks good

**Comment by LouayKamel** [comment]
@theshock9  ignore `mix deps.compile` it's not needed anymore( I will update the readme file). it's also possible to ignore the the whole compiling process as running chronicle will compile it as well. 

now please monitor  "In progress: x.dmp; Loaded amount bundles" and tell me if it stuck.

thank you for your patience

**Comment by theshock9** [comment]
k, i try it 2 for Days with different settings in importer.ex and scylla.yml but...

It stops counting. Just repeat the last `Loaded and bundles` all the time after 5 min.
And `:sys.get_state(Process.whereis(:importer)).pending` give me the same result as before `(EXIT) no process: the process is not alive ...`

If i restart the Proses it hangs on a different Bundle
Got no Errors

**Comment by LouayKamel** [comment]
@theshock you dont have to change scylla and importer settings as long there is no errors,
What the dmp file name it stops counting on?

**Comment by theshock9** [comment]
I just fine Tune Scylla for Mem usage and `max_import_concurrent` in Importer.ex

The file name is 242662.dmp

**Comment by LouayKamel** [comment]
Thank you @theshock9 so all the following dmps have been imported without any issue? 
```
6000
13157
18675
61491
150354
216223
```
I'm investigating  242662.dmp

**Comment by theshock9** [comment]
Yes, thats correct

**Comment by LouayKamel** [comment]
@theshock9 here is what is happening! 
all the dmps before 242662 have the old nonce 81-trytes structure, I applied the try/rescue method on datetime only for those files(before 242662),
therefore I will have to apply the try/rescue everywhere chronicle uses datetime (Importer, Zmq, API).

am working on it!

**Comment by LouayKamel** [comment]
@theshock9  #commit c3341b7,  so far everything in my end is working fine!

**Comment by theshock9** [comment]
On the run. I'll report if it works or not.

**Comment by theshock9** [comment]
Interim Report:
Runs like a clockwork

```
08:01:25.600 [info] In progress: 587745.dmp; Loaded 55269293 bundles
08:04:35.083 [info] Imported 587745
08:04:35.084 [info] Importing 1039245 file
08:06:25.892 [info] In progress: 1039245.dmp; Loaded 55706776 bundles
08:11:26.155 [info] In progress: 1039245.dmp; Loaded 56112229 bundles
08:16:26.295 [info] In progress: 1039245.dmp; Loaded 56511651 bundles
```

**Comment by LouayKamel** [comment]
Perfect, Thank you so much for the update!

**Comment by theshock9** [comment]
@LouayKamel 
Im sorry, but there is an other Loop on the File 1039245.dmp

**Comment by LouayKamel** [comment]
@theshock9
1039245 file is one of the largest file, does it stop counting? Is there any error in the log?

**Comment by theshock9** [comment]
It dont count anymore like the 242662.dmp
And i didnt see any errors

**Comment by LouayKamel** [comment]
Thanks, Would you please share the last lines in the log?

**Comment by LouayKamel** [comment]
hey @theshock9, btw I'm importing 1039245 with debug log enabled.
I will update you with the progress asap.

**Comment by theshock9** [comment]
Hey @LouayKamel 
Real Life got me since last Typing. Sorry
I checked the dmps.txt and there was a mess! Dont know how but 1039245 was befor 774804 and other dmp´s.
Strange

And i dont got the log because i stop the script that evening and close the console
It was not a good day. 

I updatet the "helper27.ex & importer.ex & worker27.ex" and restarted the script right now.

And i see that you guys open a new Channel on Discord "chronicle-dev"
Can i Ping you there if i got something new? So i dont Spam here

**Comment by LouayKamel** [comment]
Thank you am going to investigate why 1039245 was before 774804,
for now try to run the script with one dmp in dmps.txt at a time.
