### ISSUE TITLE
Where chronicle should been installed

### ISSUE THREAD

**Issue by lyudad** [iotaledger/chronicle#9]
1) Should chronicle been run on separate VM, or should be on same machine where full node installed
2) Where can I get data for this scylladb settings? 
cluster_name -
seeds
listen_address
auto_bootstrap
endpoint_snitch
rpc_address
3) Also step 5 in the instruction
4) tx_trytes, not clear what should be added
5) /historical/data where this folder should be located?
Thank you

**Comment by LouayKamel** [comment]
Please refer to our new Rust implementation: [chronicle.rs](https://github.com/iotaledger/chronicle.rs)
